### PR TITLE
fix: allows unpatch `off the negative` by remove/disconnect the node

### PR DESCRIPTION
**Pull request by JettHu**

### CODE REVIEW

**Comment by JettHu** [comment]
No need to toggle off anymore, just removing/disconnecting/bypass the node to unpatch it.

image

**Comment by Extraltodeus** [comment]
Hi! I just noticed your PR after doing quite an update! Would you kindly lay me down the base principle so I can try to implement it as it is now?

**Comment by JettHu** [comment]
> Hi! I just noticed your PR after doing quite an update! Would you kindly lay me down the base principle so I can try to implement it as it is now?

Oh, I'll update another version of or tonight, I'm at a party right now.

**Comment by JettHu** [comment]
The main update is: change the monkey patch function.

**Comment by JettHu** [comment]
@Extraltodeus Hey, I updated my PR to rebased your latest update.

**Comment by Extraltodeus** [comment]
Ithinnk that this could be an interesting PR for ComfyUI directly too.

I'd even go so far and say that another one in between could be useful as to be able to manipulate to cond/uncond before the CFG function.

**Comment by JettHu** [comment]
> Ithinnk that this could be an interesting PR for ComfyUI directly too.
> 
> I'd even go so far and say that another one in between could be useful as to be able to manipulate to cond/uncond before the CFG function.

Good idea. I've open a PR to ComfyUI directly before. The author might be too busy so the code review and merge was a bit slow. Since I have some new changes, I closed it. Now I think I can consider reopening this PR.

In addition, I found `cond_pos` and `cond_neg` for `square_and_norm` [here](https://github.com/Extraltodeus/ComfyUI-AutomaticCFG/blob/main/nodes.py#L140). Are these two parameters reserved for subsequent implementations?

**Comment by Extraltodeus** [comment]
> In addition, I found `cond_pos` and `cond_neg` for `square_and_norm` [here](https://github.com/Extraltodeus/ComfyUI-AutomaticCFG/blob/main/nodes.py#L140). Are these two parameters reserved for subsequent implementations?

Since I added a text input that goes through eval I wanted to see if it would be beneficial to recompute something.

If you use this for example it should work (I don't remember what is the effect however):

    (pcp/psi*sigma+cond)/2 if sigma < 14 else comfy.samplers.calc_cond_batch(args["model"], [args["cond_pos"], None], args["input"]-cond, args["timestep"], args["model_options"])[0]+cond

That's kind of why I was suggesting an in-between function since you can't really reverse the CFG function afterward. Like, if you wanted to modify the cond_pred before by doing a new compute, or anything like the perturbed attention guidance, maybe it would be possible to use the result combined with the cond_pred at each step. I mean fo experimental purposes.

So to make it clearer:

- pre_cfg_function: computes cond_pred/uncond_pred
- intermediary_cfg_function: maybe do some more compute or rework cond_pred and/or uncond_pred.
- cfg_function
- post_cfg_function

The intermediary could be a loop like the CFG function, it would take and return at least the cond_pred and uncond_pred.

Just like my functions which can transform them. Like if you've seen, somehow the squared sine of the cond_pred and uncond_pred does work. You could then chain nodes to transform them at will.

I don't have an actually precise plan for it but when I was doing these tests I was thinking of it being a practical idea for such experiments.

**Comment by Extraltodeus** [comment]
I'd even wonder if a pre-pre cfg function (with a better name) would not be such a bad idea. Stuff like the nodes that relates to the attention could then set the paraqmeters before the sampling and at each step. Like if the cross attention was higher at the beginning to ensure some maximum prompt following and then gradually decrease so to make the image more coherent as it goes could be an interesting idea.f

**Comment by JettHu** [comment]
> I'd even wonder if a pre-pre cfg function (with a better name) would not be such a bad idea. Stuff like the nodes that relates to the attention could then set the paraqmeters before the sampling and at each step. Like if the cross attention was higher at the beginning to ensure some maximum prompt following and then gradually decrease so to make the image more coherent as it goes could be an interesting idea.

Sounds cool.

**Pull request merged**
